BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Stripe;
using Stripe.Checkout;
using System.Diagnostics;
using System.Security.Claims;

namespace BulkyWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize]

    public class OrderController : Controller
	{
		private readonly IUnitofwork _unitofwork;
		[BindProperty]
		public OrderVM order { get; set; }

        public OrderController(IUnitofwork unitofwork)
        {
			_unitofwork = unitofwork;
        }
        public IActionResult Index()
		{
			
			return View();
		}
		public IActionResult Detail(int orderid) 
		{
			 order = new()
			{
				OrderDetails=_unitofwork.OrderDetail.GetAll(filter:u=>u.OrderHeaderId == orderid,includeprops:"Product"),
				OrderHeader=_unitofwork.OrderHeader.Get(filter:u=>u.Id == orderid,includeprops: "ApplicationUser")
			};
			return View(order);
		}
		[HttpPost]
		[Authorize(Roles=SD.Role_Admin+","+SD.Role_Employee )]
		public IActionResult UpdateOrderDetail()
		{
			OrderHeader tobeupdated = _unitofwork.OrderHeader.Get(o => o.Id == order.OrderHeader.Id);
			tobeupdated.StreetAddress = order.OrderHeader.StreetAddress;
			tobeupdated.PhoneNumber = order.OrderHeader.PhoneNumber;
			tobeupdated.City = order.OrderHeader.City;
			tobeupdated.PostalCode = order.OrderHeader.PostalCode;
			tobeupdated.State = order.OrderHeader.State;
			tobeupdated.Name = order.OrderHeader.Name;
			if (!string.IsNullOrEmpty(order.OrderHeader.TrackingNumber))
			{
                tobeupdated.TrackingNumber = order.OrderHeader.TrackingNumber;
            }
            if (!string.IsNullOrEmpty(order.OrderHeader.Carrier))
            {
                tobeupdated.Carrier = order.OrderHeader.Carrier;
            }
           
			_unitofwork.OrderHeader.Update(tobeupdated);
			_unitofwork.Save();
			TempData["Success"] = "Data updated successfully";
			return RedirectToAction(nameof(Detail), new {orderid=order.OrderHeader.Id});
		}
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult StartProcessing()
		{
            OrderHeader tobeupdated = _unitofwork.OrderHeader.Get(o => o.Id == order.OrderHeader.Id);
			_unitofwork.OrderHeader.UpdateStatus(id:tobeupdated.Id, orderstatus:SD.StatusInProcess,null);
			
			_unitofwork.Save();
            TempData["Success"] = "Order Shipped Successfully.";
            return RedirectToAction(nameof(Detail), new { orderid = order.OrderHeader.Id });
        }
		[HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder() 
		{
            OrderHeader tobeupdated = _unitofwork.OrderHeader.Get(o => o.Id == order.OrderHeader.Id);
			tobeupdated.Carrier = order.OrderHeader.Carrier;
			tobeupdated.TrackingNumber = order.OrderHeader.TrackingNumber;
			tobeupdated.ShippingDate = order.OrderHeader.ShippingDate;
            tobeupdated.OrderStatus = SD.StatusShipped;
            if (tobeupdated.PaymentStatus == SD.PaymentStatusDelayedPayment)
			{
                tobeupdated.PaymentDueDate = DateTime.Now.AddDays(30);
			}
            _unitofwork.OrderHeader.Update(tobeupdated);
            _unitofwork.Save();
            TempData["Success"] = "Order Shipped Successfully.";
            return RedirectToAction(nameof(Detail), new { orderid = order.OrderHeader.Id });
        }
		[HttpPost]
		[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult CancelOrder()
		{
            OrderHeader tobeupdated = _unitofwork.OrderHeader.Get(o => o.Id == order.OrderHeader.Id);
			if (tobeupdated.PaymentStatus == SD.PaymentStatusApproved)
			{
				var options = new RefundCreateOptions() { Reason=RefundReasons.RequestedByCustomer , PaymentIntent =tobeupdated.PaymentIntentId};
				var service = new RefundService();
				Refund refund= service.Create(options);
				_unitofwork.OrderHeader.UpdateStatus(tobeupdated.Id, SD.StatusCancelled, SD.StatusRefunded);
			}
			else
			{
                _unitofwork.OrderHeader.UpdateStatus(tobeupdated.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
			_unitofwork.Save();
            TempData["Success"] = "Order Cancelled Successfully.";
            return RedirectToAction(nameof(Detail), new { orderid = order.OrderHeader.Id });
        }
        [ActionName("Detail")]
        [HttpPost]
        public IActionResult Details_PAY_NOW()
        {
            order.OrderHeader = _unitofwork.OrderHeader
                .Get(u => u.Id == order.OrderHeader.Id, includeprops: "ApplicationUser");
            order.OrderDetails = _unitofwork.OrderDetail
                .GetAll(filter:u => u.OrderHeaderId == order.OrderHeader.Id, includeprops: "Product");

            //stripe logic
            var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={order.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?orderId={order.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in order.OrderDetails)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItem);
            }


            var service = new SessionService();
            Session session = service.Create(options);
            _unitofwork.OrderHeader.UpdateStripePaymentId(order.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitofwork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public IActionResult PaymentConfirmation(int orderHeaderId)
        {

            OrderHeader orderHeader = _unitofwork.OrderHeader.Get(u => u.Id == orderHeaderId);
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                //this is an order by company

                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitofwork.OrderHeader.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
                    _unitofwork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatusApproved);
                    _unitofwork.Save();
                }


            }


            return View(orderHeaderId);
        }


        #region Apicalls
        [HttpGet]
		public IActionResult GetAll(string? status)
		{
			IEnumerable<OrderHeader> orders;
            var claimsidentity = (ClaimsIdentity)User.Identity;
            var userId = claimsidentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			if (userId == SD.Role_Employee || userId==SD.Role_Admin)
			{
				orders = _unitofwork.OrderHeader.GetAll( includeprops: "ApplicationUser").ToList();
			}
			else
			{
                orders = _unitofwork.OrderHeader.GetAll(filter: o => o.ApplicationUserId == userId ,includeprops:"ApplicationUser");
            }

            switch (status)
			{
				case ("pending"): orders = orders.Where(u => u.OrderStatus == SD.StatusPending);

                        break;
                case "approved":
                    orders = orders.Where(u => u.OrderStatus == SD.StatusApproved);

                    break;
                case "inprocess":
                    orders = orders.Where(u => u.OrderStatus == SD.StatusInProcess);

                    break;
                case "completed":
                    orders = orders.Where(u => u.OrderStatus == SD.StatusShipped);

                    break;
                default:
					break;
			}


			return Json(new { data = orders });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.DataAccess.Repository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {   private readonly ApplicationDbContext _context;
        private readonly IUnitofwork _unitofwork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private IWebHostEnvironment _hostEnvironment;
        public UserController(IUnitofwork unitofwork ,UserManager<IdentityUser> userManager,RoleManager<IdentityRole> roleManager,ApplicationDbContext context)
        {
            _unitofwork = unitofwork;
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;

        }
        public IActionResult Index()
        {
            IEnumerable<Appuser> list = _unitofwork.AppUser.GetAll();

            return View(list);
        }
      
        public IActionResult Upsert(int? id)
        {

            if (id == 0 || id == null)
            {
                //create
                var appuser = new Appuser();
                return View(appuser);
            }
            else
            {
                //update
                var appuser = _unitofwork.AppUser.Get(x => x.Id == id.ToString());
                return View(appuser);
            }

        }
       
        [HttpPost]
        public IActionResult Upsert(Appuser appuser)
        {
            if (ModelState.IsValid)
            {
                
                if ((appuser.Id)=="0"|| appuser.Id.IsNullOrEmpty())
                {
                    _unitofwork.AppUser.Add(appuser);
                }
                else
                {
                    _unitofwork.AppUser.Update(appuser);
                }

                _unitofwork.Save();
                return RedirectToAction("Index");
            }

            return View(appuser);
        }
        public IActionResult RoleManagment(string userId)
        {
            
            var allroles = _roleManager.Roles.ToList();
            var allcompanies = _unitofwork.Company.GetAll().ToList();
            
            var uservm = new UserVM
            {
                user = _unitofwork.AppUser.Get(x => x.Id == userId, includeprops: "Company"),
                roles = allroles.ConvertAll(a =>
                {
                    return new SelectListItem()
                    {
                        Text = a.ToString(),
                        Value = a.ToString()
                       
                    };
                }),
                companies= allcompanies.ConvertAll(a =>
                {
                    return new SelectListItem()
                    {
                        Text = a.Name,
                        Value = a.Id.ToString()

                    };
                })
            };

            uservm.user.Role = _userManager.GetRolesAsync(uservm.user).GetAwaiter().GetResult().FirstOrDefault();
            return View(uservm);
           
        }

        [HttpPost]
        public IActionResult RoleManagment(UserVM userVM)
        {
           
           
            var oldrole = _userManager.GetRolesAsync(userVM.user).GetAwaiter().GetResult().FirstOrDefault();
            var appuser = _unitofwork.AppUser.Get(x => x.Id == userVM.user.Id);
            if (oldrole != userVM.user.Role)
            {
               
                if (userVM.user.Role == SD.Role_Company && userVM.user.CompanyId != null)
                {
                    appuser.Role = SD.Role_Company;
                    appuser.CompanyId= userVM.user.CompanyId;
                }else if (userVM.user.Role != SD.Role_Company && userVM.user.Role !=null)
                {
                    appuser.Role = userVM.user.Role;
                }
                else if (oldrole == SD.Role_Company)
                {
                    appuser.CompanyId = null;
                }

                _unitofwork.AppUser.Update(appuser);
                _unitofwork.Save();
                _userManager.RemoveFromRoleAsync(appuser ,oldrole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(appuser,userVM.user.Role).GetAwaiter().GetResult() ;
                
            }
            else
            {
                if (SD.Role_Company == oldrole && userVM.user.CompanyId != appuser.CompanyId)
                {
                    appuser.CompanyId = userVM.user.CompanyId;
                    _unitofwork.AppUser.Update (appuser);
                    _unitofwork.Save();
                }
            }
            return RedirectToAction("Index");

        }
       
        #region Api calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Appuser> list = _unitofwork.AppUser.GetAll(includeprops:"Company").ToList();
           foreach (Appuser appuser in list)
            {
                if (appuser.Role.IsNullOrEmpty())
                {
                    appuser.Role = _userManager.GetRolesAsync(appuser).GetAwaiter().GetResult().FirstOrDefault();
                    if (appuser.Company == null)
                    {
                        appuser.Company = new Company()
                        {
                            Name = "null"
                        };
                        
                    }
                }
            }
          
          
           
            return Json(new { data = list });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {
            var objfromdb =_unitofwork.AppUser.Get(x => x.Id == id);
            if (objfromdb is null)
            {
                return Json(new { Success = "false", Message = "Error" });
            }
            if (objfromdb.Role.IsNullOrEmpty())
            {
                objfromdb.Role = _userManager.GetRolesAsync(objfromdb).GetAwaiter().GetResult().FirstOrDefault();
            }
            
            if (objfromdb.LockoutEnd != null&& objfromdb.LockoutEnd > DateTime.Now)
            {
                objfromdb.LockoutEnd = DateTime.Now;
                
            }
            else
            {
                objfromdb.LockoutEnd = DateTime.Now.AddYears(100);
            }

            _unitofwork.AppUser.Update(objfromdb);
            _unitofwork.Save();
            return Json(new { Success = "true", Message = "operation successeful" });

        }

       
    } 


    #endregion
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyWeb.ViewComponents
{
    public class ShoppingCartViewComponent :ViewComponent
    {
        private readonly IUnitofwork _unitOfWork;
        public ShoppingCartViewComponent(IUnitofwork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {

                if (HttpContext.Session.GetInt32(SD.CartSession) == null)
                {
                    HttpContext.Session.SetInt32(SD.CartSession,
                    _unitOfWork.ShoppingCart.GetAll(filter:s => s.UserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.CartSession));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http 
@inject IHttpContextAccessor httpContextAccessor 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulky</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Bulky <img src="~/book.png" style="width:20px; height:20px;" /> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                      
                      @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-primary " asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="nav-link text-primary" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="nav-link text-primary" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="nav-link text-primary" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                   @*  <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a> *@
                                </ul>
                            </li>
                            
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Order Mangement</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                               
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial"> </partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_notify"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary " >
        <div class="container text-center">
            Made with love by Mohamed Alaa &nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-balloon-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8.49 10.92C19.412 3.382 11.28-2.387 8 .986 4.719-2.387-3.413 3.382 7.51 10.92l-.234.468a.25.25 0 1 0 .448.224l.04-.08c.009.17.024.315.051.45.068.344.208.622.448 1.102l.013.028c.212.422.182.85.05 1.246-.135.402-.366.751-.534 1.003a.25.25 0 0 0 .416.278l.004-.007c.166-.248.431-.646.588-1.115.16-.479.212-1.051-.076-1.629-.258-.515-.365-.732-.419-1.004a2.376 2.376 0 0 1-.037-.289l.008.017a.25.25 0 1 0 .448-.224l-.235-.468ZM6.726 1.269c-1.167-.61-2.8-.142-3.454 1.135-.237.463-.36 1.08-.202 1.85.055.27.467.197.527-.071.285-1.256 1.177-2.462 2.989-2.528.234-.008.348-.278.14-.386Z" />
            </svg> &nbsp; <a class="text-muted text-decoration-none" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script src="https://cdn.tiny.cloud/1/6mtl1rb61jbjfbnvt5q9rnwru32q82opavh4t0q1sd3ef0ro/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://kit.fontawesome.com/30953da662.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_notify.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if(TempData["Success"] != null){
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
    
}
else if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}